import { ClassRoster } from '../types';

/**
 * Teacher Roster Export Formatter
 * Converts structured class roster entities into clean, formatted markdown
 * for teachers, administrators, and lesson prep workflows.
 */
export class RosterExportService {
  /**
   * Converts a ClassRoster entity into formatted Markdown
   */
  static rosterToFormattedMarkdown(roster: ClassRoster): string {
    const { trial_class, confirmed_students, total_confirmed, available_seats } = roster;
    
    let md = `# 📋 Ottodot Class Roster: ${trial_class.title}\n\n`;
    md += `**Subject:** ${trial_class.subject}  \n`;
    md += `**Scheduled At:** ${trial_class.scheduled_at}  \n`;
    md += `**Capacity:** ${trial_class.capacity} Students (Hard Cap)  \n`;
    md += `**Confirmed Status:** ${total_confirmed}/${trial_class.capacity} (${available_seats} seats remaining)\n\n`;
    
    md += `## Confirmed Students Roster\n\n`;
    
    if (confirmed_students.length === 0) {
      md += `*No confirmed students yet for this class session.*\n`;
      return md;
    }

    md += `| # | Student Name | Age | Parent Name | Parent Email | Confirmed Timestamp |\n`;
    md += `| - | ------------ | --- | ----------- | ------------ | ------------------- |\n`;

    confirmed_students.forEach((s, idx) => {
      md += `| ${idx + 1} | **${s.student_name}** | ${s.student_age} | ${s.parent_name} | ${s.parent_email} | ${s.confirmed_at} |\n`;
    });

    md += `\n---\n*Generated by Ottodot Teacher Operations • Verified Class Data*\n`;
    return md;
  }

  static rosterToMarkdown(roster: ClassRoster): string {
    return this.rosterToFormattedMarkdown(roster);
  }

  /**
   * Converts trial classes overview into formatted Markdown
   */
  static classesOverviewToFormattedMarkdown(classes: any[]): string {
    let md = `# 🎮 Ottodot Trial Classes Overview\n\n`;
    md += `| Class ID | Title | Subject | Schedule | Confirmed | Available | Status |\n`;
    md += `| -------- | ----- | ------- | -------- | --------- | --------- | ------ |\n`;

    classes.forEach(c => {
      const avail = Math.max(0, c.capacity - c.confirmed_count);
      const statusBadge = c.confirmed_count >= c.capacity ? '🔴 FULL' : c.confirmed_count === 3 ? '🟡 1 SEAT LEFT' : '🟢 OPEN';
      md += `| \`${c.id}\` | ${c.title} | ${c.subject} | ${c.scheduled_at} | ${c.confirmed_count}/${c.capacity} | ${avail} | ${statusBadge} |\n`;
    });

    return md;
  }

  static classesOverviewToMarkdown(classes: any[]): string {
    return this.classesOverviewToFormattedMarkdown(classes);
  }
}
